title: Victor Alejandro Leiva Espinoza
# logo: /assets/img/headshot_circle.png
description: M.Sc. Data Science
theme: minimal-mistakes-jekyll

navigation:
  - title: Main Page
    url: https://vpy7.github.io/Portfolio/
    icon: home
  - title: Projects
    url: https://vpy7.github.io/Portfolio/Projects.html
    icon: folder
social_links:
  - name: GitHub
    url: https://github.com/your-username
  - name: LinkedIn
    url: https://linkedin.com/in/your-username
  - name: Twitter
    url: https://twitter.com/your-handle
